blog/urls.py
from django.urls import path
from blog.views import BlogView, DetailedView

app_name = 'blog'

urlpatterns = [
    path('',BlogView.as_view(), name='blog'),
    path('<slug:slug>-<int:pk>',DetailedView.as_view(),name='details-blog'),
]

itSystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('realizacje/', include('realizations.urls')),
    path('blog/', include('blog.urls')),
]

main/urls.py
from django.urls import path
from main.views import MainView, ContactView

app_name = 'main'

urlpatterns = [
    path('',MainView.as_view(), name='index'),
    path('contact', ContactView.as_view(), name = 'contact'),
]

realizations/urls.py
from django.urls import path
from realizations.views import RealizationsView, DetailedView

app_name = 'realizations'

urlpatterns = [
    path('',RealizationsView.as_view(), name='realizations'),
    path('<slug:slug>-<int:pk>',DetailedView.as_view(),name='details-realization' ),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
class BlogEntry(models.Model):
    title = models.CharField(max_length=64)
    image = models.URLField(max_length=256)
    short_description = models.TextField(max_length=128)
    description = models.TextField(max_length=2048)
    slug = models.SlugField(unique=False, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogEntry, self).save(*args, **kwargs)

    def __str__(self):
        return 'Nazwa: %s /id:%s' % (self.title, self.pk)

main/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class ContactModel(models.Model):
    name = models.CharField(max_length=256)
    email = models.EmailField(max_length=128)
    text = models.TextField(max_length=256)
    date_added = models.DateField(default=timezone.now)
    done = models.BooleanField(default=0)

    def __str__(self):
        return 'Mail od: %s   /id:%s' % (self.email,self.pk)

realizations/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
class Realization(models.Model):
    title = models.CharField(max_length=64)
    main_image = models.URLField(max_length=256)
    second_image = models.URLField(max_length=256)
    third_image = models.URLField(max_length=256)
    short_description = models.TextField(max_length=256)
    description = models.TextField(max_length=1024)
    slug = models.SlugField(unique=False, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Realization, self).save(*args, **kwargs)

    def __str__(self):
        return 'Nazwa: %s /id:%s' % (self.title, self.pk)

main/forms.py
from django import forms
from main.models import ContactModel
from django.core import validators

class ContactForm(forms.ModelForm):
    botcatcher = forms.CharField(required = False,
                                widget=forms.HiddenInput,
                                validators=[validators.MaxLengthValidator(0)])
    #text = forms.CharField(widget = forms.Textarea)
    class Meta:
        model = ContactModel
        fields = ('name', 'email', 'text')
        widgets = {
         'text': forms.Textarea(attrs={'cols':80,'rows':20}),
        }
        labels = {
        'name': "Imię",
        'email': "E-Mail",
        'text':"Wiadomość",
        }

blog/views.py
from django.shortcuts import render
from blog.models import BlogEntry
from django.views.generic import ListView
from django.views.generic.detail import DetailView
# Create your views here.
def blog(request):
    return render(request,'blog/index.html')

class BlogView(ListView):
    model = BlogEntry
    template_name = 'blog/index.html'
    context_object_name = 'blog_entries'
    paginate_by = 5
    queryset = BlogEntry.objects.all().order_by('-pk')

class DetailedView(DetailView):
    model = BlogEntry
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

main/views.py
from django.shortcuts import render
from main.forms import ContactForm
from throttle.decorators import throttle
from django.views import View
# Create your views here.
'''
def index(request):

    form = ContactForm()
    success = False
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            send_contact(request, form)
            form = ContactForm()
            success = True
    return render(request,'main/index.html', {'form': form, 'success':success})

@throttle(zone='default')
def send_contact(request, forms):
    forms.save(commit=True)
    return render(request,'main/index.html')
'''


class MainView(View):
    form_class = ContactForm
    initial = {'key':'value'}
    template_name = 'main/index.html'
    success = False
    def get(self, request, *args, **kwargs):
        success = False
        form = self.form_class(initial = self.initial)
        return render(request, self.template_name,{'form':form})

    @throttle(zone='default')
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save(commit=True)
            form = self.form_class(initial = self.initial)
            success = True
        return render(request, self.template_name, {'form': form, 'success':success})

class ContactView(View):
    form_class = ContactForm
    initial = {'key':'value'}
    template_name = 'main/contact.html'
    success = False
    def get(self, request, *args, **kwargs):
        success = False
        form = self.form_class(initial = self.initial)
        return render(request, self.template_name,{'form':form})

    @throttle(zone='default')
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save(commit=True)
            form = self.form_class(initial = self.initial)
            success = True
        return render(request, self.template_name, {'form': form, 'success':success})

realizations/views.py
from django.shortcuts import render
from realizations.models import Realization
from django.views.generic import ListView
from django.views.generic.detail import DetailView
# Create your views here.
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

class RealizationsView(ListView):
    model = Realization
    template_name = 'realizations/index.html'
    context_object_name = 'realizations'
    paginate_by = 6
    queryset = Realization.objects.all().order_by('-pk')

class DetailedView(DetailView):
    model = Realization
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <title>Home Page</title>
</head>
<body>
  <!-- Navbar -->
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper green">
        <a href="{% url 'main:index' %}" class="brand-logo"><img src="{% static "main/logo.png" %}" alt=""></a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="{% url 'main:index' %}">Strona główna</a></li>
          <li><a href="{% url 'realizations:realizations' %}">Realizacje</a></li>
          <li><a href="{% url 'blog:blog' %}">Blog</a></li>
        </ul>
      </div>
    </nav>
  </div>


  <ul class="sidenav" id="mobile-demo">
    <li><a class="sidenav-close" href="{% url 'main:index' %}">Strona główna</a></li>
    <li><a class="sidenav-close" href="{% url 'realizations:realizations' %}">Realizacje</a></li>
    <li><a class="sidenav-close" href="{% url 'blog:blog' %}">Blog</a></li>
  </ul>


    {% block content %}

    {% endblock %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.sidenav');
  var instances = M.Sidenav.init(elems);
  });
    </script>

  <!-- Footer -->
  <footer class="page-footer green">
           <div class="container">
             <div class="row">
              <div class="col s6 center-align">
                <h6>Przydatne linki</h6>
                <a class="white-text" href="#"><p>Polityka prywatności</p></a>
                <a href="{% url 'main:contact' %}" class="white-text"><p>Kontakt</p></a>
              </div>
              <div class="col s6 center-align">
                <h6>Śledź nas</h6>
                <a class="grey-text text-lighten-3" href="#!"><i class="fab fa-facebook-f"></i></a>
              </div>
             </div>
           </div>
           <div class="footer-copyright">
             <div class="container">
             <p class="center-align">Copyright © IT System 2018</p>
             </div>
           </div>
         </footer>
</body>
</html>

templates/blog/blogentry_detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="parallax-container">
  <div class="parallax">
    <img src="{{object.image}}">
  </div>
</div>
  <div class="container">
    <div class="row">
      <div class="col s12 center-align">
        <h5>{{object.title}}</h5>
        {% autoescape off %}
        {{ object.description }}
        {% endautoescape %}
        <p></p>
        <a href="{% url 'blog:blog' %}" class="waves-effect waves-light green darken-3 btn-small"><i class="material-icons right">chevron_left</i>Powrót</a>
      </div>
    </div>
    </div>

    <script>
    document.addEventListener('DOMContentLoaded', function() {
var elems = document.querySelectorAll('.parallax');
var instances = M.Parallax.init(elems);
});
    </script>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h1 class="center-align">Blog</h1>
  <div class="row">
    {% for entry in blog_entries %}
        <div class="row hide-on-small-only">
          <div class="col s12 valign-wrapper z-depth-3">
            <div class="col s3"><img class="responsive-img" src="{{entry.image}}" alt=""></div>
            <div class="col s5">
              <h4>{{entry.title}}</h4>
              <p class="truncate">{{entry.short_description}}</p>
            </div>
            <div class="col s4">
              <a class="green btn waves-effect waves-light btn-small" href="{%url 'blog:details-blog' pk=entry.pk slug=entry.slug %}"><i class="material-icons right">more_horiz</i>Czytaj więcej</a>
            </div>
          </div>
        </div>
        <div class="row center-align hide-on-med-and-up">
          <div class="col s8 offset-s2 z-depth-3">
            <img class="responsive-img" src="{{entry.image}}" alt="">
            <h5>{{entry.title}}</h5>
            <p class="truncate">{{entry.short_description}}</p>
            <a class="green btn waves-effect waves-light btn-small" href="{%url 'blog:details-blog' pk=entry.pk slug=entry.slug %}"><i class="material-icons right">more_horiz</i>Czytaj więcej</a>
          </div>
        </div>
    {% endfor %}
  </div>

  {% if is_paginated %}
    <ul class="pagination center-align">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active green"><span>{{ i }} <span class="sr-only"></span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
</div>

{% endblock %}

templates/main/contact.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="row">
      <!-- Kontakt -->
      <div id="contact" class="section">
        <div class="col s12 center-align">
          <h2>Kontakt</h2>
      </div>
        <div class="col s12 l6 offset-l3 center-align">
          <form method="POST">
            {{form.as_p}}
             {% csrf_token %}
            <input type="submit" class="btn green" name="" value="Wyślij">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/main/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
  <title>Home Page</title>
</head>

<body>
  <!-- Navbar -->
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper green">
        <a href="{% url 'main:index' %}" class="brand-logo"><img src="{% static "main/logo.png" %}" alt=""></a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="#about">O Nas</a></li>
          <li><a href="#services">Usługi</a></li>
          <li><a href="{% url 'realizations:realizations' %}">Realizacje</a></li>
          <li><a href="{% url 'blog:blog' %}">Blog</a></li>
          <li><a href="#contact">Kontakt</a></li>
        </ul>
      </div>
    </nav>
  </div>


  <ul class="sidenav" id="mobile-demo">
    <li><a class="sidenav-close" href="#about">O Nas</a></li>
    <li><a class="sidenav-close" href="#services">Usługi</a></li>
    <li><a class="sidenav-close" href="{% url 'realizations:realizations' %}">Realizacje</a></li>
    <li><a class="sidenav-close" href="{% url 'blog:blog' %}">Blog</a></li>
    <li><a class="sidenav-close" href="#contact">Kontakt</a></li>
  </ul>

  <div class="slider">
    <ul class="slides">
      <li>
        <img src="{% static 'main/masthead.jpg'%}" alt="">
        <div class="caption center-align">
          <h3>Najszybsze usługi informatyczne i teletechniczne</h3>
          <h5 class="light grey-text text-lighten-3">Naprawimy Twój komputer oraz dostarczymy Internet do Twojego domu</h5>
        </div>
      </li>
      <li>
        <img src="{% static 'main/masthead-2.jpg'%}" alt="">
        <div class="caption left-align">
          <h3>Tworzenie nowoczesnych stron internetowych</h3>
          <h5 class="light grey-text text-lighten-3">Optymalizacja SEO oraz standard RWD</h5>
        </div>
      </li>
    </ul>
  </div>


  <div class="container">


      <!-- Head -->
      <div class="section">
        <div class="col s12">

        </div>
      </div>
      <!-- Uslugi -->
      <div id="services" class="section">
        <div class="row">
          <div class="col s12 center-align"><h1>Usługi</h1>
          </div>
          <div class="col s12 m4 l4 center-align"><i class="material-icons large">wifi</i>
            <h5>Teletechnika</h5>
            <ul>
              <li><p>Montaż i rozbudowa instalacji internetowej LAN i WLAN (Wi-Fi)</p></li>
              <li><p>Zarabianie kabli internetowych, telefonicznych i telewizyjnych</p></li>
              <li><p>Doradztwo przy zakupie routera i jego konfiguracja</p></li>
              <li><p>Montaż routerów, switchy, reapeaterów</p></li>
            </ul>
          </div>
          <div class="col s12 m4 l4 center-align"><i class="material-icons large">web</i>
            <h5>Tworzenie stron WWW</h5>
            <ul>
              <li><p>Strony wizytówki, strony firmowe, portfolia, strony prywatne, blogi</p></li>
              <li><p>Optymalizacja SEO</p></li>
              <li><p>Standard RWD</p></li>
            </ul>
          </div>
          <div class="col s12 m4 l4 center-align"><i class="material-icons large">laptop</i>
            <h5>Serwis komputerowy</h5>
            <ul>
              <li><p>Naprawa komputerów i laptopów</p></li>
              <li><p>Instalacja oprogramowania</p></li>
              <li><p>Instalacja systemów Windows/Linux wraz ze sterownikami</p></li>
              <li><p>Składanie komputerów z nowych/używanych podzespołów</p></li>
              <li><p>Instalacja/konfiguracja drukarek</p></li>
            </ul>
          </div>
        </div>

      </div>
      <!-- Kontakt -->
      <div id="contact" class="section">
        <div class="row">
          <div class="col s12 center-align">
            <h2>Kontakt</h2>
        </div>
          <div class="col s12 center-align">
            <div class="col s3 offset-s2  z-depth-1">
              <i class="material-icons large">call</i>
              <p>666 666 666</p>
            </div>
            <div class="col s2">

            </div>
            <a class="black-text" href="mailto:itsystem@gmail.com">
            <div class="col s3 z-depth-1">
              <i class="material-icons large">email</i>
            <p><a class="black-text" href="mailto:itsystem@gmail.com">itsysytem@gmail.com</a></p>
            </div>
          </a>
          </div>
        </div>
        <div class="row">
          <div class="col s12 center-align">
            <h4>Napisz do nas!</h4>
          </div>
        </div>
        <div class="row">
          <div class="col s12 l6 offset-l3 center-align">
            <form method="POST">
              {{form.as_p}}
               {% csrf_token %}
              <input type="submit" class="btn green" name="" value="Wyślij">
            </form>
          </div>
        </div>
      </div>






    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
    {% if success %}
    <script>
      M.toast({
        html: 'Your message has been sent!'
      })
    </script>
    {% endif %}

    <script>
    document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.sidenav');
  var instances = M.Sidenav.init(elems);
  });
  document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.slider');
  var instances = M.Slider.init(elems);
});
    </script>
  </div>

  <!-- Footer -->
  <footer class="page-footer green">
           <div class="container">
             <div class="row">
              <div class="col s6 center-align">
                <h6>Przydatne linki</h6>
                <a class="white-text" href="#"><p>Polityka prywatności</p></a>
                <a href="#contact" class="white-text"><p>Kontakt</p></a>
              </div>
              <div class="col s6 center-align">
                <h6>Śledź nas</h6>
                <a class="grey-text text-lighten-3" href="#!"><i class="fab fa-facebook-f"></i></a>
              </div>
             </div>
           </div>
           <div class="footer-copyright">
             <div class="container">
             <p class="center-align">Copyright © IT System 2018</p>
             </div>
           </div>
         </footer>

</body>

</html>

templates/realizations/index.html
{% extends 'base.html'%}
{% block content %}
<div class="container">
  <div class="row">
    {% for realization in realizations %}
    <div class="col s12 l6">
    <div class="card medium">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src="{{realization.main_image}}">
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">{{realization.title}}<i class="material-icons right">more_vert</i></span>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">{{realization.title}}<i class="material-icons right">close</i></span>
      <p>{{realization.short_description}}</p>
    </div>
    <div class="card-action">
      <p><a href="{% url 'realizations:details-realization' pk=realization.pk slug=realization.slug  %}">Zobacz więcej</a></p>
    </div>
  </div>
  </div>
    {% endfor %}
  </div>
  {% if is_paginated %}
    <ul class="pagination center-align">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="disabled"><span>&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="active green"><span>{{ i }} <span class="sr-only"></span></span></li>
        {% else %}
          <li><a href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="disabled"><span>&raquo;</span></li>
      {% endif %}
    </ul>
  {% endif %}
</div>
{% endblock %}

templates/realizations/realization_detail.html
{% extends 'base.html' %}

{% block content %}

  <div class="carousel carousel-slider">
    <a class="carousel-item" href="#one!"><img src="{{object.main_image}}"></a>
    <a class="carousel-item" href="#two!"><img src="{{object.second_image}}"></a>
    <a class="carousel-item" href="#three!"><img src="{{object.third_image}}"></a>

  </div>
  <div class="container">
<div class="row">
  <div class="col s12 center-align">
    <h5>{{object.title}}</h5>
    {% autoescape off %}
    {{ object.description }}
    {% endautoescape %}
    <p></p>
    <a href="{% url 'realizations:realizations' %}" class="waves-effect waves-light green darken-3 btn-small"><i class="material-icons right">chevron_left</i>Powrót</a>

  </div>
</div>
  </div>



<script>
document.addEventListener('DOMContentLoaded', function() {
  var elems = document.querySelectorAll('.carousel');
  var instances = M.Carousel.init(elems,{
  duration:200,
  indicators: true
});

});
</script>
{% endblock %}